# Generated by Django 5.1.3 on 2024-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_leave_days_adminuser_employeeuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="approved",
            field=models.BooleanField(null=True),
        ),
    ]
