# Generated by Django 5.1.3 on 2024-11-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_leaverequest_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
