# Generated by Django 5.1.3 on 2024-11-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_leaverequest_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.CharField(
                choices=[("employee", "employee"), ("admin", "admin")],
                default="employee",
                max_length=100,
            ),
        ),
    ]
