version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    image: 2ntech:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: 123123
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: